# Generated by Django 3.1 on 2020-08-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200817_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskCompleted',
            field=models.BooleanField(default=False),
        ),
    ]
